### ISSUE TITLE
Types not converted correctly

### ISSUE THREAD

**Issue by richarddavenport** [AdrianWilczynski/CSharpToTypeScript#1]
C#
```
namespace Business.Models
{
    using System;

    public partial class DealerLender
    {
        public long DealerLenderID { get; set; }
        public string ProgramCode { get; set; }
        public string DealerCode { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateAbbreviation { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<bool> IsGenericLender { get; set; }
        public Nullable<bool> IsMBPFinanceLender { get; set; }
    }
}

```
converts to 
```
interface DealerLender {
    dealerLenderID: number;
    programCode: string;
    dealerCode: string;
    name: string;
    address1: string;
    address2: string;
    city: string;
    stateAbbreviation: string;
    zipCode: string;
    phoneNumber: string;
    createDate: string;
    updateDate: string;
    isGenericLender: Nullable<boolean>;
    isMBPFinanceLender: Nullable<boolean>;
}
```

Anyway we can convert `System.DateTime` to a `Date`?
Also nulls should be converted to one of the following:
```
isGenericLender?: boolean;
isGenericLender: boolean | null;
```
I'm willing to help as I just found this and we are trying to keep c# and typescript models in sync during our ci/cd pipeline or build process.

**Comment by AdrianWilczynski** [comment]
Thanks for the report.

I wasn't really aware of this generic nullable syntax. I'm gonna fix it. Types declared with question mark (`bool? IsGenericLender`) should work though.

As far as dates go, there isn't any way to change it right now but I can add a configuration setting that would let you pick between `string`, `Date` and maybe `string | Date`. Would that work for you?

**Comment by richarddavenport** [comment]
I was told the `Nullable<T>` syntax came from some entity framework generated code. I hadn't ever seen it before either.

The configuration option sounds great. If it's too much work, let me know what I can do to help.

I had one other question, but didn't want to open another issue. What do you think about just updating the output, rather than rewriting the file? Or if there is a way to have imports automatically inserted. I know that is a big ask.

**Comment by AdrianWilczynski** [comment]
Configuration option should be easy to add.

I'm not sure what you mean by updating the output. Do you mean only overriding old generated file if source changed so manually added imports aren't erased for no reason? I guess naive, simple way to do it would be to just check if old output ends with/contains new output and, if so, just leave it alone? Maybe that could work?

I can't really think about any way to do it more precisely since I'm not doing any TypeScript parsing or storing any state of source files. Overriding only specific parts of generated file seems kinda hard to do. Do you have some ideas?

I didn't implement imports generation yet because only CLI could make any use of it and I'm not sure if I can do it robustly enough. I think I could collect declared and required types for every file and pair them to generate imports. I'll try to play with it over the long weekend and see how it goes.

**Comment by richarddavenport** [comment]
Thanks, really appreciate it.

You could add comments to the generated code and anything modified outside the comments could be left alone. Basically if I add import statements to my files and then run the cli, the imports are removed because the file is regenerated.

**Comment by AdrianWilczynski** [comment]
Generic nullables should be fixed now. I've added configuration settings to pick output types for them (`-n|--convert-nullables-to <Null|Undefined>`) and for dates (`-d|--convert-dates-to <String|Date|Union>`).

I've also implemented your comments idea (`-p|--partial-override`). Thanks.

**Comment by richarddavenport** [comment]
Awesome! I'll give it a shot. Thanks so much!
